language: node_js

node_js:
  - 10.14.1

cache:
  bundler: true
  yarn: true
  directories:
      - node_modules

install:
  - yarn install
  - yarn add codecov -g

script:
  - yarn run test:unit
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
